import { Entity } from './types';

export const ENTITIES: Entity[] = [
  {
    "id": "sam_altman",
    "name": "Sam Altman",
    "type": "person",
    "slope": ["model", "meta"],
    "twitter": "sama",
    "twitter_url": "https://twitter.com/sama",
    "blog": "https://www.samaltman.com/",
    "rss": "https://www.samaltman.com/feed.xml",
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "OpenAI 首席执行官，GPT 系列模型缔造者，全球 AGI 方向最具影响力的领导者，被视为推动“AI 氧气时代”加速前进的关键人物。"
  },
  {
    "id": "ilya_sutskever",
    "name": "Ilya Sutskever",
    "type": "person",
    "slope": ["model"],
    "twitter": "ilyasut",
    "twitter_url": "https://twitter.com/ilyasut",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "OpenAI 联合创始人、前首席科学家，被认为是深度学习领域最重要的推动者之一，目前创立 Safe Superintelligence 致力于安全 AGI。"
  },
  {
    "id": "dario_amodei",
    "name": "Dario Amodei",
    "type": "person",
    "slope": ["model", "safety"],
    "twitter": "dario_amodei",
    "twitter_url": "https://twitter.com/dario_amodei",
    "blog": "https://www.anthropic.com",
    "rss": "https://www.anthropic.com/index.xml",
    "youtube": null,
    "github": null,
    "podcast": "https://www.anthropic.com/news",
    "intro_zh": "Anthropic 联合创始人兼 CEO，Claude 模型之父，推动以可控能力、安全性和长上下文为核心的新一代基础模型。"
  },
  {
    "id": "demis_hassabis",
    "name": "Demis Hassabis",
    "type": "person",
    "slope": ["model", "science"],
    "twitter": "demishassabis",
    "twitter_url": "https://twitter.com/demishassabis",
    "blog": "https://deepmind.google",
    "rss": null,
    "youtube": "https://www.youtube.com/@GoogleDeepMind",
    "github": null,
    "podcast": null,
    "intro_zh": "DeepMind 创始人兼 CEO，AlphaGo、AlphaFold、Gemini 的核心推动者，在“AI × 科学突破”领域影响力巨大。"
  },
  {
    "id": "andrej_karpathy",
    "name": "Andrej Karpathy",
    "type": "person",
    "slope": ["model", "education"],
    "twitter": "karpathy",
    "twitter_url": "https://twitter.com/karpathy",
    "blog": "https://karpathy.github.io/",
    "rss": null,
    "youtube": "https://www.youtube.com/@AndrejKarpathy",
    "github": "https://github.com/karpathy",
    "podcast": null,
    "intro_zh": "全球最具影响力的 AI 教学布道者，曾任 Tesla AI 总监，是解读 LLM、自动驾驶、AI 思维框架的最佳入口人物之一。"
  },
  {
    "id": "jensen_huang",
    "name": "Jensen Huang",
    "type": "person",
    "slope": ["infra"],
    "twitter": null,
    "twitter_url": null,
    "blog": "https://www.nvidia.com",
    "rss": null,
    "youtube": "https://www.youtube.com/@NVIDIA",
    "github": null,
    "podcast": null,
    "intro_zh": "英伟达创始人兼 CEO，被称为“算力之王”，通过 GPU 和 NVLink 架构推动全球 AI 基础设施革命，是整个 AI 工业化的基石人物。"
  },
  {
    "id": "nvidia",
    "name": "NVIDIA",
    "type": "company",
    "slope": ["infra"],
    "twitter": "nvidia",
    "twitter_url": "https://twitter.com/nvidia",
    "blog": "https://blogs.nvidia.com/",
    "rss": null,
    "youtube": "https://www.youtube.com/@NVIDIA",
    "github": null,
    "podcast": null,
    "intro_zh": "全球最大 AI 芯片与算力基础设施供应商，主导 GPU、NVSwitch、NVLink、CUDA 等核心生态，是 AI 时代最重要的底层公司之一。"
  },
  {
    "id": "elon_musk",
    "name": "Elon Musk",
    "type": "person",
    "slope": ["infra", "model", "geo"],
    "twitter": "elonmusk",
    "twitter_url": "https://twitter.com/elonmusk",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": "https://www.youtube.com/@TeslaPodcastHighlights",
    "intro_zh": "特斯拉、SpaceX、xAI 创始人，推动 Grok 模型和超大规模 GPU 集群建设，正通过能源、电动汽车、AI、太空建立多线斜率飞轮。"
  },
  {
    "id": "palantir",
    "name": "Palantir",
    "type": "company",
    "slope": ["agent", "context", "gov_ai", "infra"],
    "twitter": "PalantirTech",
    "twitter_url": "https://twitter.com/PalantirTech",
    "blog": "https://www.palantir.com/blog/",
    "rss": null,
    "youtube": "https://www.youtube.com/@PalantirTech",
    "github": null,
    "podcast": null,
    "intro_zh": "全球领先的政府与企业级 AI 平台供应商，以数据融合、Agent 驱动决策系统著称，是美国政府及盟友 AI 战略的核心企业之一。"
  },
  {
    "id": "peter_thiel",
    "name": "Peter Thiel",
    "type": "person",
    "slope": ["meta", "geo", "gov_ai"],
    "twitter": "peterthiel",
    "twitter_url": "https://twitter.com/peterthiel",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "硅谷最具影响力的思想家和投资人之一，Palantir 创始人，PayPal 黑帮核心人物，对科技、自由主义和国家安全有深刻影响。"
  },
  {
    "id": "alex_karp",
    "name": "Alex Karp",
    "type": "person",
    "slope": ["gov_ai", "agent", "context"],
    "twitter": null,
    "twitter_url": null,
    "blog": "https://www.palantir.com/",
    "rss": null,
    "youtube": "https://www.youtube.com/@PalantirTech",
    "github": null,
    "podcast": null,
    "intro_zh": "Palantir CEO，以独特的政治与哲学视角构建企业级 AI 和国防 AI 系统，是“AI 战略化”的关键推动者。"
  },
  {
    "id": "anduril",
    "name": "Anduril",
    "type": "company",
    "slope": ["defense", "autonomy", "hardware_ai", "infra"],
    "twitter": "AndurilTech",
    "twitter_url": "https://twitter.com/AndurilTech",
    "blog": "https://www.anduril.com/media/",
    "rss": null,
    "youtube": "https://www.youtube.com/@andurilindustries",
    "github": null,
    "podcast": null,
    "intro_zh": "美国最强 AI 国防科技公司，专注自主无人机、传感器网络、前线 AI 指挥系统，被视为未来战争的主要技术提供者。"
  },
  {
    "id": "palmer_luckey",
    "name": "Palmer Luckey",
    "type": "person",
    "slope": ["defense", "autonomy", "hardware_ai"],
    "twitter": "PalmerLuckey",
    "twitter_url": "https://twitter.com/PalmerLuckey",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Anduril 创始人、Oculus 创始人，是全球最年轻且最有创造力的硬件与国防科技创新者之一。"
  },
  {
    "id": "trae_stephens",
    "name": "Trae Stephens",
    "type": "person",
    "slope": ["defense", "geo"],
    "twitter": "traestephens",
    "twitter_url": "https://twitter.com/traestephens",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Anduril 联合创始人、Founders Fund 合伙人，专注政府技术、国防科技与战略级创新，是美国“AI 国防现代化”的关键人物。"
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "type": "company",
    "slope": ["agent", "coding", "developer_ai"],
    "twitter": "cursor_ai",
    "twitter_url": "https://twitter.com/cursor_ai",
    "blog": "https://www.cursor.com/blog",
    "rss": null,
    "youtube": "https://www.youtube.com/@cursor-ai",
    "github": null,
    "podcast": null,
    "intro_zh": "AI 原生的软件开发环境（AI IDE），通过多代理协作、代码理解与自动补全提升软件开发效率，是下一代开发者工具的代表性公司之一。"
  },
  {
    "id": "cursor_founders",
    "name": "Cursor Founders",
    "type": "person_group",
    "slope": ["agent", "coding", "developer_ai"],
    "twitter": null,
    "twitter_url": null,
    "blog": "https://www.cursor.com",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Cursor 的核心创始团队（Aidan Gomez, Ben Schmidt），来自深度学习与开发工具领域，目标是用多智能体系统重新定义软件开发体验。"
  },
  {
    "id": "spacex",
    "name": "SpaceX",
    "type": "company",
    "slope": ["infra", "space", "geo"],
    "twitter": "SpaceX",
    "twitter_url": "https://twitter.com/SpaceX",
    "blog": "https://www.spacex.com/news",
    "rss": null,
    "youtube": "https://www.youtube.com/@SpaceX",
    "github": null,
    "podcast": null,
    "intro_zh": "全球领先的航天科技公司，通过 Falcon 系列、Starship 和 Starlink 重塑全球空间基础设施，是美国太空与通信战略的核心力量之一。"
  },
  {
    "id": "databricks",
    "name": "Databricks",
    "type": "company",
    "slope": ["data", "infra", "enterprise_ai"],
    "twitter": "databricks",
    "twitter_url": "https://twitter.com/databricks",
    "blog": "https://www.databricks.com/blog",
    "rss": null,
    "youtube": "https://www.youtube.com/@databricks",
    "github": "https://github.com/databricks",
    "podcast": null,
    "intro_zh": "全球领先的企业数据 + AI 平台公司，以 Lakehouse 架构和大规模分布式训练闻名，是企业级 AI 算力与数据基础设施核心公司。"
  },
  {
    "id": "ali_ghodsi",
    "name": "Ali Ghodsi",
    "type": "person",
    "slope": ["data", "infra", "enterprise_ai"],
    "twitter": "alighodsi",
    "twitter_url": "https://twitter.com/alighodsi",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Databricks 联合创始人兼 CEO，Lakehouse 架构提出者，推动数据工程、模型训练和企业 AI 堆栈标准化。"
  },
  {
    "id": "matei_zaharia",
    "name": "Matei Zaharia",
    "type": "person",
    "slope": ["data", "infra"],
    "twitter": "matei_zaharia",
    "twitter_url": "https://twitter.com/matei_zaharia",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": "https://github.com/mateiz",
    "podcast": null,
    "intro_zh": "Databricks 联合创始人、Apache Spark 发明人，是分布式计算与 AI 数据系统领域的顶尖科学家。"
  },
  {
    "id": "david_cahn",
    "name": "David Cahn",
    "type": "person",
    "slope": ["meta", "ai_analysis"],
    "twitter": "David_Cahn",
    "twitter_url": "https://twitter.com/David_Cahn",
    "blog": "https://a16z.com",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "a16z 最具锋芒的 AI 分析者之一，以极强的技术深度和趋势判断著称，其 AI 观点被广泛引用。"
  },
  {
    "id": "naval",
    "name": "Naval Ravikant",
    "type": "person",
    "slope": ["meta", "thought", "startup"],
    "twitter": "naval",
    "twitter_url": "https://twitter.com/naval",
    "blog": "https://nav.al/",
    "rss": null,
    "youtube": "https://www.youtube.com/@naval",
    "github": null,
    "podcast": "https://nav.al/podcast",
    "intro_zh": "硅谷最有影响力的思想家之一，AngelList 创始人，以“如何致富”“清晰思维”等框架影响无数创业者和投资人。"
  },
  {
    "id": "brian_venturo",
    "name": "Brian Venturo",
    "type": "person",
    "slope": ["infra"],
    "twitter": "brianventuro",
    "twitter_url": "https://twitter.com/brianventuro",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "CoreWeave 联合创始人，专注构建高密度算力云和 GPU 数据中心，是美国 AI 算力版图中增长最快的企业领导者之一。"
  },
  {
    "id": "coreweave",
    "name": "CoreWeave",
    "type": "company",
    "slope": ["infra"],
    "twitter": "CoreWeave",
    "twitter_url": "https://twitter.com/CoreWeave",
    "blog": "https://coreweave.com/blog",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "全球发展速度最快的 AI 专用云公司之一，提供 GPU 租赁、液冷集群和 AI 数据中心，被视为 OpenAI 和美国算力战略的重要支柱。"
  },
  {
    "id": "nebius",
    "name": "Nebius",
    "type": "company",
    "slope": ["infra"],
    "twitter": "nebius_cloud",
    "twitter_url": "https://twitter.com/nebius_cloud",
    "blog": "https://nebius.com/blog",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "由前 Yandex Cloud 团队打造的新一代欧洲算力提供商，主打高性价比 GPU 云和数据驻留合规，是欧盟 AI 基建的潜力新星。"
  },
  {
    "id": "david_luan",
    "name": "David Luan",
    "type": "person",
    "slope": ["agent", "automation"],
    "twitter": "davidluan",
    "twitter_url": "https://twitter.com/davidluan",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Adept AI 联合创始人，通用操作模型（Action Model）概念提出者，自动化代理（Agent）领域的核心思想家之一。"
  },
  {
    "id": "adept_ai",
    "name": "Adept AI",
    "type": "company",
    "slope": ["agent", "automation"],
    "twitter": "AdeptAILabs",
    "twitter_url": "https://twitter.com/AdeptAILabs",
    "blog": "https://www.adept.ai/blog",
    "rss": null,
    "youtube": null,
    "github": "https://github.com/AdeptAI",
    "podcast": null,
    "intro_zh": "全球最领先的 Agent 企业之一，专注“AI 操作电脑”的方向，推动自动化工具链革命和企业工作流重构。"
  },
  {
    "id": "aravind_srinivas",
    "name": "Aravind Srinivas",
    "type": "person",
    "slope": ["agent", "search"],
    "twitter": "AravSrinivas",
    "twitter_url": "https://twitter.com/AravSrinivas",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Perplexity CEO，打造新一代 AI 搜索引擎，以检索增强生成（RAG）改写信息获取方式，是搜索领域最大的挑战者之一。"
  },
  {
    "id": "perplexity",
    "name": "Perplexity AI",
    "type": "company",
    "slope": ["agent", "search"],
    "twitter": "perplexity_ai",
    "twitter_url": "https://twitter.com/perplexity_ai",
    "blog": "https://blog.perplexity.ai/",
    "rss": null,
    "youtube": "https://www.youtube.com/@perplexity_ai",
    "github": null,
    "podcast": null,
    "intro_zh": "AI 搜索革命者，通过实时检索 + LLM 输出的模式颠覆传统搜索引擎，速度与信噪比领先整个行业。"
  },
  {
    "id": "matt_shumer",
    "name": "Matt Shumer",
    "type": "person",
    "slope": ["agent", "automation"],
    "twitter": "mattshumer_",
    "twitter_url": "https://twitter.com/mattshumer_",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "HyperWrite 创始人，推动浏览器自动化代理（Browser Agent），展示 AI 如何自主操作网页与在线服务。"
  },
  {
    "id": "hyperwrite",
    "name": "HyperWrite",
    "type": "company",
    "slope": ["agent", "automation"],
    "twitter": "HyperWriteAI",
    "twitter_url": "https://twitter.com/HyperWriteAI",
    "blog": "https://hyperwriteai.com/blog",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "自动化浏览器 AI 工具，通过多步骤网页操作展示未来 Agent 如何取代人工完成重复性在线任务。"
  },
  {
    "id": "cognition_labs",
    "name": "Cognition Labs",
    "type": "company",
    "slope": ["agent", "coding"],
    "twitter": "cognition_labs",
    "twitter_url": "https://twitter.com/cognition_labs",
    "blog": "https://www.cognition-labs.com/",
    "rss": null,
    "youtube": null,
    "github": "https://github.com/cognition-labs",
    "podcast": null,
    "intro_zh": "推出全球首款 AI 软件工程师 Devin，可自主写代码、调试、运行和提交，是自动化开发的重大拐点。"
  },
  {
    "id": "soren_rewind",
    "name": "Soren (Rewind)",
    "type": "person",
    "slope": ["memory", "personal_os"],
    "twitter": "sorenbs",
    "twitter_url": "https://twitter.com/sorenbs",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Rewind 联合创始人，推进“个人记忆系统”，让 AI 可存储、检索和理解个人全生命周期数据，是未来外脑形态的重要探索者。"
  },
  {
    "id": "rewind_ai",
    "name": "Rewind AI",
    "type": "company",
    "slope": ["memory", "personal_os"],
    "twitter": "rewindai",
    "twitter_url": "https://twitter.com/rewindai",
    "blog": "https://www.rewind.ai/blog",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "打造个人全记忆 AI，通过录屏、文本、对话构建用户时间轴，是“记忆型 AI 系统”最有前景的方向之一。"
  },
  {
    "id": "ivan_zhao",
    "name": "Ivan Zhao",
    "type": "person",
    "slope": ["memory", "workspace"],
    "twitter": "ivanhzhao",
    "twitter_url": "https://twitter.com/ivanhzhao",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "Notion 创始人，推动“工作空间即操作系统”的理念，是 AI × 生产力工具领域最具影响力的设计者之一。"
  },
  {
    "id": "notion",
    "name": "Notion",
    "type": "company",
    "slope": ["memory", "workspace"],
    "twitter": "NotionHQ",
    "twitter_url": "https://twitter.com/NotionHQ",
    "blog": "https://www.notion.so/blog",
    "rss": null,
    "youtube": "https://www.youtube.com/@NotionHQ",
    "github": null,
    "podcast": null,
    "intro_zh": "全球最受欢迎的知识管理与协作文档平台，AI 能力正在快速向“个人外脑操作系统”演进。"
  },
  {
    "id": "mustafa_suleyman",
    "name": "Mustafa Suleyman",
    "type": "person",
    "slope": ["model", "enterprise_ai"],
    "twitter": "mustafasuleymn",
    "twitter_url": "https://twitter.com/mustafasuleymn",
    "blog": null,
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "DeepMind 联合创始人之一，曾领导其伦理研发，现负责微软用户级 AI 战略，是企业级 AI 方向的重要思想者。"
  },
  {
    "id": "gina_raimondo",
    "name": "Gina Raimondo",
    "type": "person",
    "slope": ["geo", "policy"],
    "twitter": "SecRaimondo",
    "twitter_url": "https://twitter.com/SecRaimondo",
    "blog": "https://www.commerce.gov/",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "美国商务部长，主导 GPU 出口管制、CHIPS 法案与 AI 产业政策，是科技地缘政治的关键制定者。"
  },
  {
    "id": "jake_sullivan",
    "name": "Jake Sullivan",
    "type": "person",
    "slope": ["geo", "policy"],
    "twitter": null,
    "twitter_url": null,
    "blog": "https://www.whitehouse.gov/",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "美国国家安全顾问，被认为是“AI 马歇尔计划”（Genesis Mission）背后的主要推动力量，负责全球 AI 布局与供应链安全框架。"
  },
  {
    "id": "mbs",
    "name": "Mohammed bin Salman",
    "type": "person",
    "slope": ["geo", "energy"],
    "twitter": null,
    "twitter_url": null,
    "blog": "https://www.vision2030.gov.sa/",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "沙特王储，通过 PIF 推动数百亿美元级别的 AI 和数据中心投资，将中东转变为“AI 新能源中心”。"
  },
  {
    "id": "paul_graham",
    "name": "Paul Graham",
    "type": "person",
    "slope": ["meta", "startup"],
    "twitter": "paulg",
    "twitter_url": "https://twitter.com/paulg",
    "blog": "http://www.paulgraham.com/",
    "rss": null,
    "youtube": null,
    "github": null,
    "podcast": null,
    "intro_zh": "硅谷最重要的思想家之一、Y Combinator 创始人，长期影响创业方向、产品哲学与技术趋势判断。"
  },
  {
    "id": "marc_andreessen",
    "name": "Marc Andreessen",
    "type": "person",
    "slope": ["meta", "vc"],
    "twitter": "pmarca",
    "twitter_url": "https://twitter.com/pmarca",
    "blog": "https://a16z.com/",
    "rss": null,
    "youtube": "https://www.youtube.com/@a16z",
    "github": null,
    "podcast": "https://a16z.com/podcasts/",
    "intro_zh": "a16z 创始合伙人，硅谷最激进的技术乐观主义者之一，是 AI、加密、基础设施和生物科技投资的核心引领者。"
  }
];

// Extract unique slopes for filtering
export const UNIQUE_SLOPES = Array.from(
  new Set(ENTITIES.flatMap(e => e.slope))
).sort();